.travis.yml
Gopkg.lock
Gopkg.toml
README.md
config.go
ecspresso.go

Follow to ECS update.
Service Definition JSON allows more keys.
- launchType (for Fargate!)
- networkConfiguration
- placementStrategy

Support to launchType and networkConfiguration.

---

ecspresso.go
service.go

Show events on deploy like status.
```console
2017/12/26 23:46:32 myapp/default Starting deploy
Service: myapp
Cluster: default
TaskDefinition: myapp:2
Deployments:
PRIMARY myapp:2 desired:1 pending:0 running:1
Events:
2017/12/26 23:46:33 myapp/default desired count: 0
2017/12/26 23:46:33 myapp/default Updating service...
2017/12/26 23:46:33 myapp/default Waiting for service stable...(it will take a few minutes)
2017/12/26 23:47:14 myapp/default  PRIMARY myapp:2 desired:0 pending:0 running:1
2017/12/26 23:46:45 (service myapp) has begun draining connections on 1 tasks.
2017/12/26 23:46:45 (service myapp) deregistered 1 targets in (target-group arn:aws:
elasticloadbalancing:us-east-1:99999999999:targetgroup/myapp/ab929826e570edd5)
2017/12/26 23:47:19 myapp/default Service is stable now. …
```

show events on deploy.

---

README.md
ecspresso.go
ecspresso_test.go
tests/td-plain.json
tests/td.json

Accept a plain task definition JSON.
At first, load JSON as complex format(for compatibility), and then fallback to plain format.

Load a plain task definition.

---

cmd/ecspresso/main.go
ecspresso.go
options.go

Deregister a rolled back task definition when rollback is over successfully.

add --deregister-task-definition to rollback command

---

.gitignore
README.md
config.go
ecspresso.go

- enable setting `desiredCount` in service_definition json
- only override `desiredCount` when option (--tasks) is specified

configurable desiredCount on service creation

---

Gopkg.lock
Gopkg.toml
config.go
ecspresso.go

Supports HealthCheckGracePeriodSeconds, PlatformVersion and SchedulingStrategy for service attributes.

Update to aws-sdk-go v1.14.5

---

cmd/ecspresso/main.go

In order to dynamically change the setting of ECS cluster, Changed to use environment variable in config.yaml as well.
In my case I am deploying from CircleCI(e.g. push to deploy/`develpment` branch -> deploy to xxx-`development` cluster).

Change config.Load to config.LoadWithEnv

---

ecspresso.go

ECS API says,
> InvalidParameterException:
> The daemon scheduling strategy does not support a desired count for services.
> Remove the desired count value and try again

Set nil to DesiredCount when SchedulingStrategy is DAEMON.

---

Gopkg.lock
Gopkg.toml

Support for ECS Secrets.
https://aws.amazon.com/jp/about-aws/whats-new/2018/11/aws-launches-secrets-support-for-amazon-elastic-container-servic/

update to aws-sdk-go v1.15.78

---

go.mod

- https://github.com/aws/aws-sdk-go/releases/tag/v1.19.3
> This release of Amazon Elastic Container Service (Amazon ECS) introduces support for external deployment controllers for ECS services with the launch of task set management APIs. Task sets are a new primitive for controlled management of application deployments within a single ECS service.
- https://github.com/aws/aws-sdk-go/releases/tag/v1.19.22
> This release of Amazon Elastic Container Service (Amazon ECS) introduces additional task definition parameters that enable you to define secret options for Docker log configuration, a per-container list contains secrets stored in AWS Systems Manager Parameter Store or AWS Secrets Manager.

update to aws-sdk-go v1.19.26

---

cmd/ecspresso/main.go
ecspresso.go
options.go

This options is useful to invoke a long term task and exit immediately.

add --no-wait to run command.

---

README.md
cmd/ecspresso/main.go
ecspresso.go
options.go

I don't hope to register a new task definition every time run tasks.
When --skip-task-definition is set, run tasks using the task definition set in the service.

Add --overrides, --count and --skip-task-definition to run command.

---

ecspresso.go

fix for #33 
I enabled the Timeout setting by Waiter's MaxAttempts.
Timeout setting has no effect on aws-sdk waiter. 
If the time to `Service Stable` takes 10 minutes or more, ecspresso will fail in 10 minutes even if a value larger than 10 minutes is set in the Timeout setting.
The reason for failure in 10 minutes is due to the default value in aws-sdk
https://github.com/aws/aws-sdk-go/blob/master/service/ecs/waiters.go#L82-L83

add timeout config when call aws-sdk

---

ecspresso.go
go.mod

Add comment for #34
https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md
> v1.23.13 (2019-08-30)
> - This release of Amazon Elastic Container Service (Amazon ECS) introduces support for modifying the cluster settings for existing clusters, which enables you to toggle whether Container Insights is enabled or not. Support is also introduced for custom log routing using the ECS FireLens integration.
> v1.23.3 (2019-08-16)
> - This release of Amazon Elastic Container Service (Amazon ECS) introduces support for controlling the usage of swap space on a per-container basis for Linux containers.
> v1.21.0 (2019-07-18)
> - This release of Amazon Elastic Container Service (Amazon ECS) introduces support for cluster settings. Cluster settings specify whether CloudWatch Container Insights is …

Update to aws-sdk-go-v1.23.13

---

ecspresso.go

This fix is around timeout attempts introduced in #34, that change is insufficient due to the boundary value problem. Due to this problem, the timeout occurs earlier than the setting value.
We should calculate the value of attempts by dividing, rounding up and adding 1. The reason for adding 1 is that the first attempt is performed without waiting for the delay.
It is difficult to explain, so here are some examples:
| timeout sec | attempts now (problem) | attempts desired (fixed) |
|-------------|--------------|-----------------|
| 14          |  0           |     2           |  
| 15          |  1           |     2           |
| 16          |  1           |     3           |

fix calculation way of attempts

---

ecspresso.go

`newTd` (= registered new task definition) is not defined on `--dry-run` mode.

fix panic on run --dry-run

---

cmd/ecspresso/main.go
ecspresso.go
options.go

The `ecspresso` will wait for the service to stabilize after deployed. However, sometimes we want the `ecspresso` to finish as soon as a service update request is issued.
With this change, the `--no-wait` option has been added so that the `ecspresso` will be terminated as soon as a service update request is issued. Instead, we can use the new `wait` subcommand to wait for service stability.

add `wait` subcommand and add `--no-wait` option to `deploy`, `create` and `rollback` subcommands

---

cmd/ecspresso/main.go
ecspresso.go
options.go
service.go

When auto-scaling settings are attached to ECS service, set --tasks=0 for deploy command will be canceled by application auto-scaling.
To avoid that behavior, We can set a "suspendState" to the scalableTarget.
`ecspresso deploy --suspend-auto-scaling` resisters "suspendState" to true only when "scalableTarget" is available.

Add -suspend-auto-scaling option to deply sub command.

---

cmd/ecspresso/main.go
ecspresso.go
go.mod

When ecspresso have insufficient IAM permissions for auto-scaling,
"status" and "deploy" sub command ignore errors at access to auto-scaling.
deploy --(no-)suspend-auto-scaling options becomes to work only when specified explicitly.
v0.10.0 failed to "status" and "deploy" when lack of permissions for "application-autoscaling".

Keep compatibility with v0.9.0.

---

ecspresso.go
tests/td-plain.json
tests/td.json

ProxyConfiguration is required to use AppMesh integration at ECS.
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ProxyConfiguration.html

feature: register proxy configuration

---

cmd/ecspresso/main.go
deploy.go
ecspresso.go

Accidentally set desired count to 0 when without --tasks option. (v0.13.0〜v0.13.1)

fix desired count on deploy

---

README.md
cmd/ecspresso/main.go
deploy.go
ecspresso.go
go.mod
go.sum
options.go
rollback.go

Update to latest aws-sdk-go (to support new ECS features).
Update service attributes on deploy with `--update-service` flag.
Enable to change CapacityProviderStrategy, NetworkConfiguration, HealthCheckGracePeriodSeconds and PlatformVersion of the service.

Fargate Spot support.

---

ecspresso.go

Hi. 
I'd like to swtich profile without AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.
So, enabled sharedConfig. 
see reference https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#SharedConfigState
```
$ AWS_PROFILE=hogehoge go run cmd/ecspresso/main.go init --region ap-northeast-1 --cluster test-cluster --service test-service --config config.yml 
```

Enable sharedConfig

---

go.mod
go.sum

Update aws-sdk-go to v1.28.5.
https://github.com/aws/aws-sdk-go/releases/tag/v1.28.5
> Release v1.28.5 (2020-01-17)
> service/ecs: Updates service API, documentation, and paginators
> This release provides a public preview for specifying Amazon EFS file systems as volumes in your Amazon ECS task definitions.

Support for ECSVolumeConfiguration

---

deploy.go

`deploy` command is crashed when deploying service having `CODE_DEPLOY` deployment controller without `--tasks` option.
```
$ ecspresso deploy --config dev_api_config.yml --rollback-events DEPLOYMENT_FAILURE
2020/02/07 16:44:43 xxxxxx/xxxxxx Starting deploy
Service: xxxxxx
Cluster: xxxxxx
TaskDefinition: xxxxxx:5
TaskSets:
PRIMARY xxxxxx:5 desired:1 pending:0 running:1
Events:
2020/02/07 16:44:45 xxxxxx/xxxxxx Creating a new task definition by ecs-task-def.json
2020/02/07 16:44:45 xxxxxx/xxxxxx Registering a new task definition...
2020/02/07 16:44:45 xxxxxx/xxxxxx Task definition is registered xxxxxx:8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1650108]
goroutine 1 [running]: …
```

Fix the deployment by CODE_DEPLOY

---

ecspresso.go

Sometimes, I set task definition like below, that has multiple containers.
then, I execute ecspresso run.
Command "./app1" failed, but ecspresso could not catch the error.
Because ecspresso only got the "describe task" of one container (name: app2) 
```
{
"containerDefinitions": [
{
"command": [
"./app1"
],
"environment": [],
"image": "app1/xxxxxxxxxxxxxxx",
"name": "app1",
.....
},
{
"image": "app2/xxxxxxxxxxxxxxx",
"name": "app2",
.....
}
],
"cpu": "256",
"volumes": []
.....
}
```

To check the "exit codes" of multiple containers in the executed task definition

---

README.md
cmd/ecspresso/main.go
ecspresso.go
go.mod
go.sum
options.go

add `diff` command.
```console
$ ecspresso diff --config=path/to/config.yml
2020/06/17 17:44:38 app/cluster Creating a new task definition by task-definition/service.json
{
"containerDefinitions": [
{
"command": [
"agent"
],
-      "cpu": 0,
"dockerLabels": {
"name": "app"
},
"environment": [
{
"name": "AWS_REGION",
"value": "ap-northeast-1"
+        },
+        {
+          "name": "FOO",
+          "value": "this is foo"
}
],
"essential": true,
-      "image": "path/to/image/app:1234",
+      "image": "path/to/image/app:abcd",
"logConfiguration": {
"logDriver": "awslogs",
"options": {
"awslogs-group": "/service",
"awslogs-region": "ap-northeast-1",
"awslogs-stream-prefix": ""
}
},
-      "mountPoints": [],
"name": "app",
-      "portMappings": [],
"secrets": [
{
"name": "SECRET_KEY", …
```

add diff command

---

config_test.go
deploy.go
diff.go
diff_test.go
ecspresso.go
export_test.go
util.go

- Fix --dry-run output format from `.String()` to JSON.
- Reduce `diff` elements which essentially the same thing.
- for example, "0.25 vCPU" equals to "256" in taskDefinition.cpu.
- Sort elements in (task|container)Definitions by reflect package.
- (internal changes) `LoadServiceDefinition` returns `*ecs.Service` instead of `*ecs.CreateServiceInput`

Fix --dry-run output format

---

diff.go
diff_test.go

Currently, 
1. Sort containerDefinitions in taskDefinition.
2. Inject default values into each containerDefinitions.
But the sort order was effected by injected default values.
This PR sorts after default values injected for stable sort order.

sort containerDefinitions after default values injected

---

go.mod
go.sum
plugin.go

- https://github.com/kayac/go-config/pull/30
- https://github.com/fujiwara/tfstate-lookup/releases/tag/v0.0.12
go-config/tfstate was removed. Switch to tfstate-lookup/tfstate.FuncMap() to get a template.FuncMap.

Use tfstate-lookup directly instead of go-config/tfstate

---

deploy.go

refs #152
Even if a new DeploymentInfo exists, it not used to be applied.

Remove codes to find DeploymentInfo from current taskset.

---

cmd/ecspresso/main.go
config.go
config_test.go
ecspresso.go
ecspresso_test.go
tests/ci/config.yaml
tests/test.yaml

fixes #140
Load task/service-definition files based on the relative path from a config file.
At v0, resolved from a current (ecspresso running) path.

resolve task/service def with relpath from a config file.

---

deploy.go
deploy_test.go
ecspresso.go
export_test.go
options.go

Fix for #131 
At deploy, ecspresso sets a desiredCount to ECS service by the following priority.
1. --tasks CLI option.
1. `desiredCount` in a service definition if defined.
1. (Unchanged)

Apply desired count in service def

---

cmd/ecspresso/main.go
deploy.go
ecspresso.go
options.go

This option is useful when we have registered a new task definition by running `ecspresso run` before `ecspresso deploy`, or when we want to deploy multiple services with the same task definition.

add --latest-task-definition option to deploy with latest task definition

---

config.go
deploy.go
diff.go
ecspresso.go
tests/ci/Makefile

At v0.x, service_definition is not necessarily in config. But v0.99.x required service_definition. Fix it.
Updating service attributes runs only when service_definition file exists and a difference exists between service_definition and ECS service.

Allow no service_definition in config.

---

appspec.go
cmd/ecspresso/main.go
options.go

output AppSpec YAML to STDOUT.
```
$ ecspresso --config config.yaml appspec --help
usage: ecspresso appspec [<flags>]
output AppSpec YAML for CodeDeploy to STDOUT
Flags:
--help                      Show context-sensitive help (also try --help-long and --help-man).
--config=CONFIG             config file
--debug                     enable debug log
--task-definition="latest"  use task definition arn in AppSpec (latest, current or Arn)
```
```
$ ecspresso --config config.yaml appspec
version: "0.0"
Resources:
- TargetService:
Type: AWS::ECS::Service
Properties:
TaskDefinition: arn:aws:ecs:ap-northeast-1:123456789012:task-definition/ecspresso-test:123
LoadBalancerInfo:
ContainerName: nginx
ContainerPort: 80
PlatformVersion: LATEST
NetworkConfiguration:
AwsvpcConfiguration:
AssignPublicIp: …
```

add appspec sub command
