kayac/ecspresso

- ecspresso.go
> Set all attributes of task definition to registeration input.

- Makefile
- README.md
- cmd/ecspresso/main.go
- ecspresso.go
- options.go
Add `--tasks` and `--skip-task-definition` to deploy sub command.
> Set desired count at deploy.

- cmd/ecspresso/main.go
- ecspresso.go
- options.go
Support `--force-new-deployment` for updating service.
> Force new deployment

- Gopkg.lock
- README.md
- cmd/ecspresso/main.go
- ecspresso.go
- options.go
> Add delete sub command.

- ecspresso.go
ECS API says...
> If using the awsvpc networkMode in the task definition, a networkConfiguration is required.
> Set a networkConfiguration to ecs.UpdateServiceInput.

- README.md
- cmd/ecspresso/main.go
- ecspresso.go
- options.go
- service.go
- run tasks such as db migrations
- show logs if using awslogs
> Add command for Run task

- .travis.yml
- config.go
- ecspresso.go
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html
> Add ServiceRegistries to support service discovery.

- .travis.yml
- Makefile
- go.mod
update to aws-sdk-go v1.17.13 (DependsOn support).
> migrate to vgo

- ecspresso.go
Wait for UpdateService affect to DescribeServices response.
> Sleep 3 sec after update service.

- README.md
- cmd/ecspresso/main.go
- ecspresso.go
- options.go
> Add wait subcommand, -no-wait option to create, deploy, rollback.

- README.md
- cmd/ecspresso/main.go
- config.go
- ecspresso.go
- options.go
`ecspresso register`  registers a task definition without service.
> Add register sub command.

- go.mod
> update to aws-sdk-go v1.25.4

- cmd/ecspresso/main.go
- deploy.go
- ecspresso.go
- go.mod
equivalent to deploy --skip-task-definiton --force-new-deployment
> add refresh command

- .circleci/config.yml
- .github/workflows/release.yml
- Makefile
We cannot use GitHub Actions currently. Enable to use CircleCI for CI & release.
> add config for CircleCI

- Makefile
- orb.yml
```yaml
version: 2.1
orbs:
ecspresso: fujiwara/ecspresso@0
jobs:
deploy:
docker:
- image: circleci/...
steps:
- ecspresso/install
- run:
command: |
...
```
> Add CircleCI Orb

- ecspresso.go
> Revert "To check the "exit codes" of multiple containers in the executed task definition"

- cmd/ecspresso/main.go
- ecspresso.go
- options.go
refs #105
watch a container that exits with non zero status.
> add --watch-container to run command

- ecspresso.go
The purpose of this PR is to be enable timeout setting for Run task, similar to [add timeout config when call aws-sdk by hajimeni · Pull Request #34 · kayac/ecspresso](https://github.com/kayac/ecspresso/pull/34)
this code base is very similar to: https://github.com/kayac/ecspresso/blob/master/ecspresso.go#L559-L572
> add timeout config for RunTask

- Makefile
- appspec/spec.go
- deploy.go
- orb.yml
- rollback.go
- tests/ci/config.yaml
Fix CodeDeploy AppSpec at `deploy --update-service` specified.
This PR enables to set networkConfiguration and platformVersion to CodeDeploy app spec.
> Codedeploy appspec

- .github/workflows/release.yml
- README.md
- action.yml
Easy install on GitHub Actions.
> Add action.yml

- Makefile
- deploy.go
- ecspresso.go
> Wait codedeploy

- cmd/ecspresso/main.go
- deploy.go
- deploy_test.go
- go.mod
- go.sum
- tests/ci/Makefile
- default --update-service is true.
- Fix broken at deploy / refresh sub command.
> V1 fix broken
